// utils/Data.js
export const BarData = [
  {
    id: 1,
    year: 2016,
    userGain: 80000,
    userLost: 823,
  },
  {
    id: 2,
    year: 2017,
    userGain: 45677,
    userLost: 345,
  },
  {
    id: 3,
    year: 2018,
    userGain: 78888,
    userLost: 555,
  },
  {
    id: 4,
    year: 2019,
    userGain: 90000,
    userLost: 4555,
  },
  {
    id: 5,
    year: 2020,
    userGain: 4300,
    userLost: 234,
  },
];

export const newUserData = [
  {
    id: "1",
    userID: "AS45219566",
    userLinkedin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Call scheduled",
  },
  {
    id: "2",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Payment made",
  },
  {
    id: "3",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Mail Sent",
  },
  {
    id: "4",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Payment made",
  },
  {
    id: "5",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Mail Sent",
  },
  {
    id: "6",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Payment made",
  },
  {
    id: "7",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Mail Sent",
  },
  {
    id: "8",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Call scheduled",
  },
  {
    id: "9",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Call scheduled",
  },
];

export const onboardingUserData = [
  {
    id: "1",
    userID: "AS45219566",
    userLinkedin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "Form Filled",
  },
  {
    id: "2",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "Form Filled",
  },
  {
    id: "3",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "Onboarding mail sent",
  },
  {
    id: "4",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "Form Filled",
  },
  {
    id: "5",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "Onboarding mail sent",
  },
  {
    id: "6",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "Onboarding mail sent",
  },
  {
    id: "7",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "Call scheduled",
  },
  {
    id: "8",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "Call scheduled",
  },
  {
    id: "9",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "Call scheduled",
  },
];

export const verifiedUserData = [
  {
    id: "1",
    userID: "AS45219566",
    userLinkedin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "KYC done",
  },
  {
    id: "2",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "KYC done",
  },
  {
    id: "3",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "Contribution form done",
  },
  {
    id: "4",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "Contribution form done",
  },
  {
    id: "5",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "Nomination form done",
  },
  {
    id: "6",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "Contribution form done",
  },
  {
    id: "7",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "Nomination form done",
  },
  {
    id: "8",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "Nomination form done",
  },
  {
    id: "9",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    status: "KYC done",
  },
];

// syndicate All request  table
export const syndicateAllRequestTableData = [
  {
    id: "1",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    status: "New",
    email: "sahil123@gmail.com",
    mobileNumber: "9876543210",
  },
  {
    id: "2",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    status: "New",
    email: "sahil456@gmail.com",
    mobileNumber: "9876543210",
  },
  {
    id: "3",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    status: "Accepted",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
  },
  {
    id: "4",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    status: "Rejected",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
  },

  {
    id: "5",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    status: "New",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
  },
  {
    id: "6",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    status: "New",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
  },
  {
    id: "7",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    status: "New",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
  },
  {
    id: "8",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    status: "Rejected",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
  },
  {
    id: "9",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    status: "New",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
  },
  {
    id: "10",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    status: "New",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
  },
];

export const syndicateRequestTableData = [
  {
    id: "1",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Akash Nagpal",
    status: "New",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
  },
  {
    id: "2",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    status: "New",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
  },
];

export const acceptedSyndicatesDataTable = [
  {
    id: "1",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    investorNumberLP: "60",
    Deals: "5",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
  },
  {
    id: "2",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    investorNumberLP: "60",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    Deals: "5",
  },
  {
    id: "3",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    investorNumberLP: "60",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    Deals: "5",
  },
  {
    id: "4",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    investorNumberLP: "60",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    Deals: "5",
  },

  {
    id: "5",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    investorNumberLP: "60",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    Deals: "5",
  },
  {
    id: "6",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    investorNumberLP: "60",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    Deals: "5",
  },
  {
    id: "7",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    investorNumberLP: "60",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    Deals: "5",
  },
  {
    id: "8",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    investorNumberLP: "60",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    Deals: "5",
  },
  {
    id: "9",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    investorNumberLP: "60",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    Deals: "5",
  },
  {
    id: "10",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    investorNumberLP: "60",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    Deals: "5",
  },
];

export const rejectedSyndicatesDataTable = [
  {
    id: "1",

    syndicateName: "Zecat",
    startupLogo: "/images/massive.png",
    reasonForRejection:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
    email: "sahil123@gmail.com",
    mobileNumber: "9876543210",
    syndicateLeadName: "Shailesh Vickram Singh",
  },
  {
    id: "2",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    reasonForRejection:
      "Lorem ipsum dolor sit amet, consectetur adipiscing leu.",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    syndicateLeadName: "Shailesh Vickram Singh",
  },
  {
    id: "3",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    reasonForRejection:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    syndicateLeadName: "Shailesh Vickram Singh",
  },
  {
    id: "4",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    reasonForRejection:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    syndicateLeadName: "Shailesh Vickram Singh",
  },

  {
    id: "5",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    reasonForRejection:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    syndicateLeadName: "Shailesh Vickram Singh",
  },
  {
    id: "6",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    reasonForRejection:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    syndicateLeadName: "Shailesh Vickram Singh",
  },
  {
    id: "7",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    reasonForRejection:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    syndicateLeadName: "Shailesh Vickram Singh",
  },
  {
    id: "8",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    reasonForRejection:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    syndicateLeadName: "Shailesh Vickram Singh",
  },
  {
    id: "9",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    reasonForRejection:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    syndicateLeadName: "Shailesh Vickram Singh",
  },
  {
    id: "10",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    reasonForRejection:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
    email: "sahil@gmail.com",
    mobileNumber: "9876543210",
    syndicateLeadName: "Shailesh Vickram Singh",
  },
];

export const syndicateDetailData = [
  {
    id: "1",
    startupLogo: "/images/massive.png",
    syndicateName: "Zecat",
    dateCreated: "June 2023",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",

    investmentCard: [
      {
        logo: "/images/nilogo.png",
        companyName: "Ace Green Recycling",
        companyIndustry: "Battery Recycling",
        companyLocation: "Bengaluru | 2023",
      },
      {
        logo: "/images/nilogo.png",
        companyName: "Ace Green Recycling",
        companyIndustry: "Battery Recycling",
        companyLocation: "Bengaluru | 2023",
      },
      {
        logo: "/images/nilogo.png",
        companyName: "Ace Green Recycling",
        companyIndustry: "Battery Recycling",
        companyLocation: "Bengaluru | 2023",
      },
      {
        logo: "/images/nilogo.png",
        companyName: "Ace Green Recycling",
        companyIndustry: "Battery Recycling",
        companyLocation: "Bengaluru | 2023",
      },
      {
        logo: "/images/nilogo.png",
        companyName: "Ace Green Recycling",
        companyIndustry: "Battery Recycling",
        companyLocation: "Bengaluru | 2023",
      },
    ],

    syndicateDealCardData: [
      {
        deal_type: "live",
        companyLogo: "/images/nilogo.png",

        id: "01",
        sector: "Industrial decarbonizaton",
        name: "Ace Green Recycling",
        sub: "Battery Recycling",
        place: "Bengaluru",
        founding_year: "2023",
        asking_price: "20,00,000",
        commited_price: "15,56,500",
        syndicate: "GoMassive",
        syndicateLogo: "/images/massive.png",
        deal_live_at: "23-02-2024",
        is_commited: "false",
      },
      {
        deal_type: "live",
        companyLogo: "/images/nilogo.png",

        id: "01",
        sector: "Industrial decarbonizaton",
        name: "Ace Green Recycling",
        sub: "Battery Recycling",
        place: "Bengaluru",
        founding_year: "2023",
        asking_price: "20,00,000",
        commited_price: "15,56,500",
        syndicate: "GoMassive",
        syndicateLogo: "/images/massive.png",
        deal_live_at: "23-02-2024",
        is_commited: "false",
      },
    ],

    stage: "Seed",
    industry: "Climate Tech",
    syndicateLeadName: "Shailesh Vickram Singh",
    status: "New",
    email: "sahil123@gmail.com",
    mobileNumber: "9876543210",
  },
];

export const syndicateMembersTableData = [
  {
    id: "1",
    userID: "AS45219566",
    userLinkedin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Call scheduled",
  },
  {
    id: "2",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Payment made",
  },
  {
    id: "3",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Mail Sent",
  },
  {
    id: "4",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Payment made",
  },
  {
    id: "5",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Mail Sent",
  },
  {
    id: "6",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Payment made",
  },
  {
    id: "7",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Mail Sent",
  },
  {
    id: "8",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Call scheduled",
  },
  {
    id: "9",
    userID: "AS45219566",
    userLinkdin: "linkdin",
    userName: "Sahil",
    userEmail: "sahil@gmail.com",
    userCategory: "Individual",
    dateJoined: "22/01/2024",
    status: "Call scheduled",
  },
];

// dealTableData
export const dealTableData = [
  {
    id: "01",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    approvalStatus: "Rejected",
    email: "sahil12345@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "02",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    approvalStatus: "New",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "03",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    approvalStatus: "New",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "04",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    approvalStatus: "Rejected",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "05",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    approvalStatus: "Rejected",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "06",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    approvalStatus: "Accepted",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "07",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    approvalStatus: "Accepted",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "01",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    approvalStatus: "New",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "09",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    approvalStatus: "Accepted",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
];

// accepted Deal Table Data
export const acceptedDealTableData = [
  {
    id: "01",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "02",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "03",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "04",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "05",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "06",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "07",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "01",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
  {
    id: "09",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
  },
];

// accepted Deal Table Data
export const rejectedDealTableData = [
  {
    id: "01",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
    dealRejectReason:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
  },
  {
    id: "02",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
    dealRejectReason:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
  },
  {
    id: "03",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
    dealRejectReason:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
  },
  {
    id: "04",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
    dealRejectReason:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
  },
  {
    id: "05",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
    dealRejectReason:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
  },
  {
    id: "06",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
    dealRejectReason:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
  },
  {
    id: "07",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
    dealRejectReason:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
  },
  {
    id: "01",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
    dealRejectReason:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
  },
  {
    id: "09",
    requestDate: "22/01/2024",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    dealCreatorPic: "/images/insvs.png",
    dealCreatorName: "Shailesh Vickram",
    dealCreatorPosition: "GoMassive Syndicate",
    dealCreatorSyndicate: "Syndicate Lead",
    dealStatus: "Live Now",
    email: "sahil123@gmail.com",
    mobile: "9988776655",
    dealRejectReason:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus libero eu.",
  },
];

export const dealData = [
  {
    id: 0,
    deal_type: "live",
    sector: "Industrial decarbonizaton",
    name: "Ace Green Recycling",
    sub: "Battery Recycling",
    place: "Bengaluru",
    founding_year: "2023",
    asking_price: "20,00,000",
    commited_price: "15,56,500",
    syndicate: "GoMassive",
    deal_live_at: "23-02-2024",
    is_commited: "false",
  },
  {
    id: 1,
    deal_type: "closed",
    sector: "Industrial decarbonizaton",
    name: "Ace Green Recycling",
    sub: "Battery Recycling",
    place: "Bengaluru",
    founding_year: "2023",
    asking_price: "20,00,000",
    commited_price: "15,56,500",
    syndicate: "GoMassive",
    deal_live_at: "23-02-2024",
    is_commited: "false",
  },
  {
    id: 2,
    deal_type: "live",
    sector: "Industrial decarbonizaton",
    name: "Ace Green Recycling",
    sub: "Battery Recycling",
    place: "Bengaluru",
    founding_year: "2023",
    asking_price: "20,00,000",
    commited_price: "15,56,500",
    syndicate: "GoMassive",
    deal_live_at: "23-02-2024",
    is_commited: "true",
  },
  {
    id: 3,
    deal_type: "close",
    sector: "Industrial decarbonizaton",
    name: "Ace Green Recycling",
    sub: "Battery Recycling",
    place: "Bengaluru",
    founding_year: "2023",
    asking_price: "20,00,000",
    commited_price: "15,56,500",
    syndicate: "GoMassive",
    deal_live_at: "23-02-2024",
    is_commited: "false",
  },
  {
    id: 4,
    deal_type: "live",
    sector: "Industrial decarbonizaton",
    name: "Ace Green Recycling",
    sub: "Battery Recycling",
    place: "Bengaluru",
    founding_year: "2023",
    asking_price: "20,00,000",
    commited_price: "15,56,500",
    syndicate: "GoMassive",
    deal_live_at: "23-02-2024",
    is_commited: "true",
  },
];

export const committedAccountTableData = [
  {
    id: "01",
    name: "Akash",
    logo: "/images/insvs.png",
    email: "sahil12345@gmail.com",
    mobile: "9988776655",
companyName:"zecat",
    dropdownAmount: "1,02,00,000",
    investedAmount: "1,00,00,000",
    feeType: "2%",
    ShareClassOfUnits: "A",
    status: "Partially Invested",
  },
  {
    id: "02",
    name: "Akash",
    logo: "/images/insvs.png",
    email: "sahil12345@gmail.com",
    mobile: "9988776655",
    dropdownAmount: "1,02,00,000",
    investedAmount: "1,00,00,000",
    feeType: "2%",
    ShareClassOfUnits: "A",
    status: "Invested",
  },
  {
    id: "03",
    name: "Akash",
    logo: "/images/insvs.png",
    email: "sahil12345@gmail.com",
    mobile: "9988776655",
    dropdownAmount: "1,02,00,000",
    investedAmount: "1,00,00,000",
    feeType: "2%",
    ShareClassOfUnits: "A",
    status: "Cancelled",
  },
  {
    id: "04",
    name: "Akash",
    logo: "/images/insvs.png",
    email: "sahil12345@gmail.com",
    mobile: "9988776655",
    dropdownAmount: "1,02,00,000",
    investedAmount: "1,00,00,000",
    feeType: "2%",
    ShareClassOfUnits: "A",
    status: "Invested",
  },
  // dropdownAmount: "1,02,00,000",
  {
    id: "05",
    name: "Akash",
    logo: "/images/insvs.png",
    email: "sahil12345@gmail.com",
    mobile: "9988776655",
    dropdownAmount: "1,02,00,000",
    investedAmount: "1,00,00,000",
    feeType: "2%",
    ShareClassOfUnits: "A",
    status: "Committed",
  },
  {
    id: "06",
    name: "Ranbir Kapoor",
    logo: "/images/insvs.png",
    email: "ranbirkapoor@gmail.com",
    mobile: "9988776655",
    dropdownAmount: "1,02,00,000",
    investedAmount: "1,00,00,000",
    feeType: "2%",
    ShareClassOfUnits: "A",
    status: "Cancelled",
  },
  {
    id: "01",
    name: "Sahil",
    logo: "/images/insvs.png",
    email: "sahil12345@gmail.com",
    mobile: "9988776655",
    dropdownAmount: "1,02,00,000",
    investedAmount: "1,00,00,000",
    feeType: "2%",
    ShareClassOfUnits: "A",
    status: "Committed",
  },
  {
    id: "08",
    name: "Akash Nagpal",
    logo: "/images/insvs.png",
    email: "akash@gmail.com",
    mobile: "9988776655",
    dropdownAmount: "1,02,00,000",
    investedAmount: "1,00,00,000",
    feeType: "2%",
    ShareClassOfUnits: "A",
    status: "Cancelled",
  },
];

export const ledgerCompanyData = [
  {
    id: "01",
    email: "sahil12345@gmail.com",
    mobile: "9988776655",
    logo: "/images/nilogo.png",
    companyName: "Ace Green Recycling",
    companyIndustry: "Battery Recycling",
    companyLocation: "Bengaluru | 2023",
    status: "Partially Invested",
  },
  {
    id: "02",
    name: "Akash",
    logo: "/images/insvs.png",
    email: "sahil12345@gmail.com",
    mobile: "9988776655",
    dropdownAmount: "1,02,00,000",
    investedAmount: "1,00,00,000",
    feeType: "2%",
    ShareClassOfUnits: "A",
    status: "Invested",
  },
  {
    id: "03",
    name: "Akash",
    logo: "/images/insvs.png",
    email: "sahil12345@gmail.com",
    mobile: "9988776655",
    dropdownAmount: "1,02,00,000",
    investedAmount: "1,00,00,000",
    feeType: "2%",
    ShareClassOfUnits: "A",
    status: "Cancelled",
  },
  {
    id: "04",
    name: "Akash",
    logo: "/images/insvs.png",
    email: "sahil12345@gmail.com",
    mobile: "9988776655",
    dropdownAmount: "1,02,00,000",
    investedAmount: "1,00,00,000",
    feeType: "2%",
    ShareClassOfUnits: "A",
    status: "Invested",
  },
  // dropdownAmount: "1,02,00,000",
  {
    id: "05",
    name: "Akash",
    logo: "/images/insvs.png",
    email: "sahil12345@gmail.com",
    mobile: "9988776655",
    dropdownAmount: "1,02,00,000",
    investedAmount: "1,00,00,000",
    feeType: "2%",
    ShareClassOfUnits: "A",
    status: "Committed",
  },
  {
    id: "06",
    name: "Ranbir Kapoor",
    logo: "/images/insvs.png",
    email: "ranbirkapoor@gmail.com",
    mobile: "9988776655",
    dropdownAmount: "1,02,00,000",
    investedAmount: "1,00,00,000",
    feeType: "2%",
    ShareClassOfUnits: "A",
    status: "Cancelled",
  },
  {
    id: "01",
    name: "Sahil",
    logo: "/images/insvs.png",
    email: "sahil12345@gmail.com",
    mobile: "9988776655",
    dropdownAmount: "1,02,00,000",
    investedAmount: "1,00,00,000",
    feeType: "2%",
    ShareClassOfUnits: "A",
    status: "Committed",
  },
  {
    id: "08",
    name: "Akash Nagpal",
    logo: "/images/insvs.png",
    email: "akash@gmail.com",
    mobile: "9988776655",
    dropdownAmount: "1,02,00,000",
    investedAmount: "1,00,00,000",
    feeType: "2%",
    ShareClassOfUnits: "A",
    status: "Cancelled",
  },
];


